export const constantText = {
  monthYearDateFormat: "MMM YYYY",
  defaultDateFormat: "DD MM YYYY",
  yearMonthDateFormat: "YYYY-MM-DD",
  yes: "Yes",
  no: "No",
  active: "Active",
  inActive: "In Active",
  projectPage: {
    search: "Search for Project",
    customer: "Customer",
    pm: "Manager",
    isSupport: "Is Support",
    status: "Status",
    startDate: "Start Date",
  },
  peoplePage: {
    search: "Search for People",
    role: "Role",
    skills: "Skills",
    country: "Country",
    technology: "Technology",
  },
  somethingWentWrong: "Something went wrong",
};
